OC.L10N.register(
    "webhook_listeners",
    {
    "Webhooks" : "Webhooks",
    "Omni365 Webhook Support" : "Omni365 Webhook Support",
    "Send notifications to external services whenever something important happens, like when files are changed or updated." : "Send notifications to external services whenever something important happens, like when files are changed or updated.",
    "Set up webhooks that automatically notify external services whenever certain events - like file changes - occur \n        within Omni365. By configuring these webhooks, administrators can specify which actions in their Omni365 instance \n        should trigger notifications and where those notifications should be sent, enabling seamless integration with other platforms \n        and automating workflows.\n\n        The app works by monitoring Omni365’s event system and dispatching HTTP requests (webhooks) containing relevant event \n        data to the specified endpoints whenever a configured event takes place. This approach makes it easy to connect Omni365 \n        with external tools, allowing for real-time interactions without needing to manually check for updates or changes.\n\n        Administrators can configure webhook listeners via the app's OCS API. The app also provides a command-line tool to list \n        currently configured webhooks. There are no Web UI settings." : "Set up webhooks that automatically notify external services whenever certain events - like file changes - occur \n        within Omni365. By configuring these webhooks, administrators can specify which actions in their Omni365 instance \n        should trigger notifications and where those notifications should be sent, enabling seamless integration with other platforms \n        and automating workflows.\n\n        The app works by monitoring Omni365’s event system and dispatching HTTP requests (webhooks) containing relevant event \n        data to the specified endpoints whenever a configured event takes place. This approach makes it easy to connect Omni365 \n        with external tools, allowing for real-time interactions without needing to manually check for updates or changes.\n\n        Administrators can configure webhook listeners via the app's OCS API. The app also provides a command-line tool to list \n        currently configured webhooks. There are no Web UI settings.",
    "Omni365 webhook support" : "Omni365 webhook support"
},
"nplurals=2; plural=(n != 1);");
