name: Release

on:
  push:
    tags:
      - 'v*'   # Déclenchement dès qu'un tag commençant par v est push

permissions:
  contents: write

jobs:
  release:
    if: startsWith(github.ref_name, 'v')   # Condition basée sur le tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt update -y && sudo apt install php composer -y

      - name: Build release
        run: sudo chmod +x build/npm-post-build.sh && make all package

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create "$GITHUB_REF_NAME" server.tgz
